
      version: '3.7'
      services:
        postgres_db:
          image: postgres
          container_name: postgres
          restart: always
          environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=alexis
            - POSTGRES_DB=mydatabase
          networks:
            - generator
          ports:
            - 5432:5432
          volumes:
            - postgres_data:/var/lib/postgresql/data
      networks: 
        generator:
          ipam:
            driver: default
            config:
              - subnet: 192.168.0.0/24
      volumes:
        postgres_data:
          driver: local
          driver_opts:
            type: none
            o: bind
            device: /c/Users/alexi/generator/postgres
    
